apiVersion: v1
kind: Service
metadata:
  label:
    name: ovirt-engine
  name: ovirt-engine
spec:
  ports:
    - name: engine
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: engine-tls
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: spice-proxy
      port: 3128
      protocol: TCP
      targetPort: 3128
  selector:
    app: ovirt-engine
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
