apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ovirt-engine
  name: ovirt-engine
spec:
  containers:
    - image: rmohr/spice-squid
      name: spice-proxy
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 3128
          protocol: TCP

    - image: docker.io/bronhaim/miq-postgresql:9.5
      name: postgres
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
      env:
        - name: POSTGRESQL_USER
          value: engine
        - name: POSTGRESQL_PASSWORD
          value: engine
        - name: POSTGRESQL_DATABASE
          value: engine

    - image: docker.io/bronhaim/ovirt-engine:4.1
      name: ovirt-engine
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
      volumeMounts:
        - mountPath: /etc/pki/ovirt-engine
          name: certs
        - mountPath: /var/lib/ovirt-engine/backups
          name: backups
        - mountPath: /usr/share/ovirt-engine/ui-plugins/
          name: plugins
      env:
        - name: POSTGRES_USER
          value: engine
        - name: POSTGRES_PASSWORD
          value: engine
        - name: POSTGRES_DB
          value: engine
        - name: POSTGRES_HOST
          value: localhost
        - name: POSTGRES_PORT
          value: "5432"
        - name: OVIRT_FQDN
          value: ovirt-engine.192.168.42.143.xip.io
        - name: OVIRT_PASSWORD
          value: engine
        - name: OVIRT_PKI_ORGANIZATION
          value: oVirt
        - name: SPICE_PROXY
          value: http://172.17.0.1:3128

  volumes:
    - emptyDir: {}
      name: certs
    - emptyDir: {}
      name: backups
    - emptyDir: {}
      name: pgdata
    - emptyDir: {}
      name: plugins
