apiVersion: v1
kind: ConfigMap
metadata:
  name: ovirt-engine-config
  namespace: default
data:
  postgres.password: postgres
  engine.fqdn: ovirt-engine
  engine.password: engine
  spice.gateway.address: http://192.168.200.2:3128
