apiVersion: v1
kind: Service
metadata:
  name: ovirt-engine
spec:
  externalIPs:
    - 192.168.200.2
  ports:
    - name: engine
      port: 80
      protocol: TCP
      targetPort: engine
    - name: engine-tls
      port: 443
      protocol: TCP
      targetPort: engine-tls
    - name: spice-proxy
      port: 3128
      protocol: TCP
      targetPort: spice-proxy
  selector:
    app: ovirt-engine
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
