apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ovirt-engine-persist
  name: ovirt-engine-persist
spec:
  containers:
    - image: rmohr/spice-squid
      name: spice-proxy
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 3128
          protocol: TCP

    - image: rmohr/ovirt-postgres:latest
      name: postgres
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
      env:
        - name: POSTGRES_USER
          value: engine
        - name: POSTGRES_PASSWORD
          value: engine
        - name: POSTGRES_DATABASE
          value: engine

    - image: docker.io/bronhaim/ovirt-engine:4.0
      name: ovirt-engine
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
      volumeMounts:
        - mountPath: /etc/pki/ovirt-engine
          name: certs
        - mountPath: /var/lib/ovirt-engine/backups
          name: backups
        - mountPath: /usr/share/ovirt-engine/ui-plugins/
          name: plugins
      env:
        - name: POSTGRES_USER
          value: engine
        - name: POSTGRES_PASSWORD
          value: engine
        - name: POSTGRES_DB
          value: engine
        - name: POSTGRES_HOST
          value: localhost
        - name: POSTGRES_PORT
          value: "5432"
        - name: ENGINE_FQDN
          value: dhcp-1-110.tlv.redhat.com
        - name: OVIRT_FQDN
          value: dhcp-1-110.tlv.redhat.com
        - name: OVIRT_PASSWORD
          value: engine
        - name: OVIRT_PKI_ORGANIZATION
          value: oVirt
        - name: SPICE_PROXY
          value: http://172.17.0.1:3128

  volumes:
    - name: certs
      nfs:
        path: "/nfsshare/certs"
        server: dhcp-0-174.tlv.redhat.com
    - name: backups
      nfs:
        path: "/nfsshare/backups"
        server: dhcp-0-174.tlv.redhat.com
    - name: pgdata
      nfs:
        path: "/nfsshare/pgdata"
        server: dhcp-0-174.tlv.redhat.com
    - name: plugins
      nfs:
        path: "/nfsshare/plugins"
        server: dhcp-0-174.tlv.redhat.com
