apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv
  annotations:
    pv.beta.kubernetes.io/gid: "999"
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /exports/pgdata
    server: 192.168.200.2
  persistentVolumeReclaimPolicy: Recycle
